In [1]:
%autosave 60

Autosaving every 60 seconds

In [2]:
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import matplotlib.pylab as pylab
import matplotlib.pyplot as plt
from pandas import get_dummies
import matplotlib as mpl
import xgboost as xgb
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import warnings
import sklearn
import scipy
import numpy
import json
import sys
import csv
import os

In [3]:
print('matplotlib: {}'.format(matplotlib.__version__))
print('sklearn: {}'.format(sklearn.__version__))
print('scipy: {}'.format(scipy.__version__))
print('seaborn: {}'.format(sns.__version__))
print('pandas: {}'.format(pd.__version__))
print('numpy: {}'.format(np.__version__))
print('Python: {}'.format(sys.version))

matplotlib: 3.0.3
sklearn: 0.22
scipy: 1.2.1
seaborn: 0.9.0
pandas: 0.24.2
numpy: 1.16.2
Python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]

In [4]:
sns.set(style='white', context='notebook', palette='deep')
pylab.rcParams['figure.figsize'] = 12,8
warnings.filterwarnings('ignore')
mpl.style.use('ggplot')
sns.set_style('white')
%matplotlib inline

In [5]:
#Importing data into dataframe
df =  pd.read_csv('C://Data/all.csv')

In [6]:
df.drop(['ph_PostMigratedHere','ph_UnknownSuggestionEvent','ph_QuestionMerged','ph_PostMigrated','ph_PostMigrated','p_Wiki','ph_QuestionUnmerged','ph_PostDisassociated','ph_SuggestedEditApplied','ph_UnknownDevRelatedEvent','ph_VoteNullificationByDev','ph_PostTweeted','ph_PostUnmigrated','ph_UnknownModeratorEvent','ph_UnknownEvent','ph_CommentDiscussionMovedToChat','p_PrivilegeWiki','p_WikiPlaceholder'], axis= 1, inplace=True);

In [13]:
pd.set_option('display.expand_frame_repr', False)

In [14]:
df.head(12)

          Id country  AboutMe_length  activity_in_months  UpVotes  DownVotes  Reputation  Views  badges  Q_comments  ...  ph_CommunityOwned  ph_PostLocked  ph_PostUnlocked  ph_QuestionUnprotected  ph_QuestionProtected  ph_PostNoticeRemoved  ph_PostNoticeAdded  ph_PostMergeSource  ph_PostMigratedAway  ph_PostMergeDestination
4    1440631     usa            32.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
6    4036517     usa            30.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
8    8425017     usa           124.0                 0.0        0          0           1      1       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
10   2572342     usa           215.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
12   5076320     usa           223.0                 0.0        0          0           1      2       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
14   6778823     usa            84.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
15  10979075     usa           212.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
16   9284448     usa           163.0                 0.0        0          0           1      1       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
18   6649561     usa           163.0                 0.0        0          0           1      1       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
23   8447838     usa           154.0                 0.0        0          0           6      1       4         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
24   4870490     usa           193.0                 0.0        0          0           1      1       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN
27   3006800     usa            19.0                 0.0        0          0           1      0       1         NaN  ...                NaN            NaN              NaN                     NaN                   NaN                   NaN                 NaN                 NaN                  NaN                      NaN

[12 rows x 39 columns]

In [8]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]

In [9]:
df.head()

,Id,country,AboutMe_length,activity_in_months,UpVotes,DownVotes,Reputation,Views,badges,Q_comments,...,ph_CommunityOwned,ph_PostLocked,ph_PostUnlocked,ph_QuestionUnprotected,ph_QuestionProtected,ph_PostNoticeRemoved,ph_PostNoticeAdded,ph_PostMergeSource,ph_PostMigratedAway,ph_PostMergeDestination
4,1440631,usa,32.0,0.0,0,0,1,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4036517,usa,30.0,0.0,0,0,1,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8425017,usa,124.0,0.0,0,0,1,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2572342,usa,215.0,0.0,0,0,1,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5076320,usa,223.0,0.0,0,0,1,2,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Modify the graph above by assigning each species an individual color.
g = sns.FacetGrid(df, hue="Survived", col="Pclass", margin_titles=True,
                  palette={1:"seagreen", 0:"gray"})
g=g.map(plt.scatter, "Fare", "Age",edgecolor="w").add_legend();